DROP TABLE IF EXISTS ORDER_ITEM;
  
CREATE TABLE ORDER_ITEM (
  OIID INT AUTO_INCREMENT PRIMARY KEY,
  product_code VARCHAR(50) NOT NULL,
  product_name VARCHAR(50) NOT NULL,
  quantity int NOT NULL,
  OID int NOT NULL
);
